# Generated by Django 4.1.8 on 2023-04-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=32)),
                ("team_name", models.CharField(max_length=32)),
                ("tricode", models.CharField(max_length=5)),
                ("logo_url", models.URLField()),
            ],
        ),
    ]
