# Generated by Django 4.1.8 on 2023-04-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_school_primary_color_school_secondary_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="athletics_url",
            field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="school",
            name="logo_url",
            field=models.URLField(default=""),
        ),
    ]
