# Generated by Django 4.1.8 on 2023-05-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("start_dt", models.DateTimeField(verbose_name="show start time")),
                ("call_dt", models.DateTimeField(verbose_name="call time")),
            ],
        ),
    ]
