# Generated by Django 4.1.8 on 2023-05-01 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_show"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("director", "Director"),
                            ("producer", "Producer"),
                            ("technical-director", "Technical Director"),
                            ("replay", "Replay"),
                            ("graphics", "Graphics"),
                            ("camera-op", "Camera Op"),
                            ("talent", "Talent"),
                            ("b-roll", "B Roll"),
                            ("utility", "Utility"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.show"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
